name: Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    strategy:
      matrix:
        formula: [ clipp, poac, toml11 ]
    steps:
    - uses: actions/checkout@v1
    - run: brew update
    - run: brew install --verbose --build-bottle Formula/${{ matrix.formula }}.rb
    - run: brew test Formula/${{ matrix.formula }}.rb
    #- run: brew audit --strict Formula/${{ matrix.formula }}.rb
