name: Homebrew

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formula:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        formula: [ plog, toml11 ]
    steps:
    - uses: actions/checkout@v2.3.4
    - run: brew update
    - run: brew install --debug --verbose ./Formula/${{ matrix.formula }}.rb
    - run: brew test Formula/${{ matrix.formula }}.rb
    #- run: brew audit --strict Formula/${{ matrix.formula }}.rb

  head_only_formula:
    runs-on: macOS-latest
    strategy:
      fail-fast: false
      matrix:
        formula: [ clipp, mitama-cpp-result, poac ]
    steps:
    - uses: actions/checkout@v2.3.4
    - run: brew update
    - run: brew audit --new-formula ./Formula/${{ matrix.formula }}.rb
#     - run: brew install --HEAD --debug --verbose ./Formula/${{ matrix.formula }}.rb
    #- run: brew test Formula/${{ matrix.formula }}.rb
    #- run: brew audit --strict Formula/${{ matrix.formula }}.rb
