name: Homebrew

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  formula:
    runs-on: macOS-latest
    strategy:
      matrix:
        formula: [ plog, toml11 ]
    steps:
    - uses: actions/checkout@v2.3.4
    - run: brew update
    - run: brew install --debug --verbose ./Formula/${{ matrix.formula }}.rb
    - run: brew test Formula/${{ matrix.formula }}.rb
    #- run: brew audit --strict Formula/${{ matrix.formula }}.rb

  head_only_formula:
    runs-on: macOS-latest
    strategy:
      matrix:
        formula: [ clipp, cpp-netlib, mitama-cpp-result, poac ]
    steps:
    - uses: actions/checkout@v2.3.4
    - run: brew update
    - run: brew install --HEAD --debug --verbose ./Formula/${{ matrix.formula }}.rb
    #- run: brew test Formula/${{ matrix.formula }}.rb
    #- run: brew audit --strict Formula/${{ matrix.formula }}.rb
