name: Homebrew

on: [push, pull_request]

jobs:
  build:
    runs-on: macOS-latest
    steps:
    - uses: actions/checkout@v1
    - run: brew update
    - run: \cp -f poac.rb $(brew --repo)/Library/Taps/homebrew/homebrew-core/Formula/
    - run: brew install --build-from-source poac
    - run: brew test poac
    - run: brew audit --strict poac
    - run: poac --version
    
    - name: Slack Notification
      uses: homoluctus/slatify@master
      if: always()
      with:
        type: ${{ job.status }}
        job_name: '*${{ github.workflow }} build*'
        url: ${{ secrets.SLACK_WEBHOOK }}
        username: 'GitHub Action (${{ github.workflow }})'
        commit: true
        token: ${{ secrets.GITHUB_TOKEN }}
