name: Homebrew

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  formula:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-11, macos-12, ubuntu-18.04, ubuntu-20.04, ubuntu-22.04 ]
        formula: [ poac ]
    steps:
    - uses: actions/checkout@v3
    - run: brew update
    - run: brew install --build-from-source --debug --verbose ./Formula/${{ matrix.formula }}.rb
    - run: brew test Formula/${{ matrix.formula }}.rb
    - run: brew audit --strict Formula/${{ matrix.formula }}.rb

  # head_only_formula:
    # runs-on: macos-11
    # strategy:
      # fail-fast: false
      # matrix:
        # formula: [ poac ]
    # steps:
    # - uses: actions/checkout@v3
    # - run: brew update
    # - run: brew install --HEAD --debug --verbose ./Formula/${{ matrix.formula }}.rb
    #- run: brew test Formula/${{ matrix.formula }}.rb
    #- run: brew audit --strict Formula/${{ matrix.formula }}.rb
